<?php

use com\cminds\listmanager\plugin\options\Options;


?>


<?php
echo do_shortcode( '[cminds_free_activation id="cmlm"]' );

?>
<div style="height:25px;"></div>

<div class="cmlm">
    <form method="post">

 

    <h2 class="nav-tab-wrapper">
      <a href="#cmlm-tab-plugin-upgrade" data-for="plugin-upgrade" class="nav-tab">Upgrade</a>
      <a href="#cmlm-tab-plugin-options" data-for="plugin-options" class="nav-tab">Plugin Options</a> 
       <a href="#cmlm-tab-plugin-installation" data-for="plugin-installation" class="nav-tab">Installation Guide</a> 
       <a href="#cmlm-tab-plugin-shortcode" data-for="plugin-shortcode" class="nav-tab">Shortcodes</a> 
    </h2>
          <div data-role="tab" data-tab="plugin-upgrade" style="display: none;">
              <table class="form-table"><tbody>
                        <tr>
                            <td> <?php echo do_shortcode( '[cminds_upgrade_box id="cmlm"]' ); ?></td>
                        </tr>
                    </tbody></table>
            </div>

        <div data-role="tab" data-tab="plugin-options" style="display: none;">
        <table class="form-table">
            <tr>
                <th scope="row"><label for="columns_count">Number of columns *</label></th>
                <td>
                    <input name="columns_count" type="number" min="1" max="10" id="columns_count" value="<?php echo intval(Options::getOption('columns_count')); ?>" class="regular-text" required="required">
                    <p class="description">Number of columns generated by plugin.</p>
                </td>
            </tr>

            <tr>
                <th scope="row"><label for="favicons_local_cache">Favicons local cache</label></th>
                <td>
                    <input type="checkbox" id="favicons_local_cache" onchange="jQuery(this).next().val(this.checked ? 1 : 0)" <?php echo intval(Options::getOption('favicons_local_cache')) ? 'checked="checked"' : ''; ?> />
                    <input type="hidden" name="favicons_local_cache" value="<?php echo intval(Options::getOption('favicons_local_cache')); ?>" />
                    <p class="description">
                        If enabled images with favicons will be locally saved as attached - this options <strong>is not</strong> recommend if you curate large lists (may cause performance issues).
                        <br />
                        Favicon for link is cached during adding or updating link entry.
                    </p>
                </td>
            </tr>
            <tr>
                <th scope="row"><label for="links_rel_nofollow">No follow</label></th>
                <td>
                    <input type="checkbox" id="links_rel_nofollow" onchange="jQuery(this).next().val(this.checked ? 1 : 0)" <?php echo intval(Options::getOption('links_rel_nofollow')) ? 'checked="checked"' : ''; ?> />
                    <input type="hidden" name="links_rel_nofollow" value="<?php echo intval(Options::getOption('links_rel_nofollow')); ?>" />
                    <p class="description">
                        If enabled <code>rel="nofollow"</code> will be added to links.
                    </p>
                </td>
            </tr>
            <tr>
                <th scope="row"><label for="links_target_blank">Open in a new window or tab</label></th>
                <td>
                    <input type="checkbox" id="links_target_blank" onchange="jQuery(this).next().val(this.checked ? 1 : 0)" <?php echo intval(Options::getOption('links_target_blank')) ? 'checked="checked"' : ''; ?> />
                    <input type="hidden" name="links_target_blank" value="<?php echo intval(Options::getOption('links_target_blank')); ?>" />
                    <p class="description">
                        If enabled linked documents will be opened in a new window or tab.
                    </p>
                </td>
            </tr>
        </table>
</div>

        

          <div data-role="tab" data-tab="plugin-installation" style="display: none;">
              <table class="form-table"><tbody>
                        <tr>
                            <td><?php echo do_shortcode( '[cminds_free_guide id="cmlm"]' ); ?></td>
                        </tr>
                    </tbody></table>
            </div>


          <div data-role="tab" data-tab="plugin-shortcode" style="display: none;">
              <table class="form-table"><tbody>
                         <tr>

                <p>
        <strong>Available Shortcodes:</strong> <code>[cm_list_manager]</code>

    </p>
    </tr>
                    </tbody></table>
            </div>


    
        <input type="hidden" name="cmlm_action_update" value="1" />
        <input type="hidden" name="nonce" value="<?php echo wp_create_nonce('cmlm_action_update'); ?>" />
        <?php submit_button(); ?>
        <small>* - required fields</small>

    </form>
</div>

<script type="text/javascript">
    (function ($) {
        "use strict";
        $('.cmlm .nav-tab').on('click', function () {
            $('.cmlm .nav-tab').removeClass('nav-tab-active');
            $(this).addClass('nav-tab-active');
            $('.cmlm *[data-role="tab"]').hide();
            $('.cmlm *[data-role="tab"][data-tab="' + $(this).data('for') + '"]').show();
        });
        if ($('.cmlm a[href="' + window.location.hash + '"]').click().length != 1) {
            $('.cmlm a.nav-tab').first().click();
        }
        $('.cmlm input[type="submit"]').on('click', function () {
            if ($('.cmlm form').find(':invalid')) {
                var tab = $('.cmlm form').find(':invalid').first().parents('*[data-role="tab"]').data('tab');
                $('.cmlm').find('a[data-for="' + tab + '"]').click();
            }
        });
    })(jQuery);
</script>